### ISSUE TITLE
Gickmark - Product Design Roadmap

### ISSUE THREAD

**Issue by damms005** [damms005/devdb-vscode#13]
Gickmark will be bringing direction for the design of DevDB, and will also, by hte side, contribute to HTML/CSS/Figma.

The immediate actionable tasks are:
- [ ] Gickmark to fix date for the kick-off meeting where specifics of implementation will be finalized
- [ ] Dami to setup and configure Vuepress
- [ ] Gickmark to study [Vuepress](https://vuepress.vuejs.org/guide). The aim is to get ready for putting together the docs from day 1
